version: '3'
services:
  mysql:
    image: mysql
    container_name: sl-mysql
    restart: always
    networks:
      - sl-net
    ports:
      - "13306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root123

  face:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8081:8899"
    volumes:
      - ../smartLabFiles/:/usr/smartLabFiles/
    depends_on:
      - mysql
    restart: always
    networks:
      - sl-net
networks:
  sl-net:
    external: false