version: '3'
services:
  mysql:
    image: mysql
    container_name: sl-mysql
    restart: always
    networks:
      - sl-net
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root123

networks:
  sl-net:
    external: false